version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: npm install -g truffle
      - run: npm install -g ganache-cli
      - run: ganache-cli & truffle test
