version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: sudo npm install -g truffle
      - run: sudo npm install -g ganache-cli
      - run: ganache-cli &
      - run: truffle test
