version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: npm npm install truffle
      - run: npm npm install ganache-cli
      - run: ganache-cli & truffle test
